/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: f6612f87b7cc17cfd384b23fcd618045)
interface __BaseEnv_CloudflareEnv {
	HYPERDRIVE: Hyperdrive;
	ASSETS: Fetcher;
	DATABASE_URL: string;
	NEXTAUTH_SECRET: string;
	NEXTAUTH_URL: string;
	APP_BASE_URL: string;
	STORAGE_ENDPOINT: string;
	STORAGE_BUCKET: string;
	STORAGE_ACCESS_KEY: string;
	STORAGE_SECRET_KEY: string;
	STORAGE_PUBLIC_BASE_URL: string;
	PAYMENT_PROVIDER: string;
	PAYMENT_WEBHOOK_ALLOWED_IPS: string;
	MOCK_WEBHOOK_SECRET: string;
	ECPAY_MERCHANT_ID: string;
	ECPAY_HASH_KEY: string;
	ECPAY_HASH_IV: string;
	ECPAY_ENDPOINT: string;
	NEWEBPAY_MERCHANT_ID: string;
	NEWEBPAY_HASH_KEY: string;
	NEWEBPAY_HASH_IV: string;
	TAPPAY_PARTNER_KEY: string;
	TAPPAY_MERCHANT_ID: string;
	TAPPAY_APP_ID: string;
	TAPPAY_APP_KEY: string;
	ORDER_EXPIRE_MINUTES: string;
	BUSINESS_DAY_CUTOFF: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "NEXTAUTH_SECRET" | "NEXTAUTH_URL" | "APP_BASE_URL" | "STORAGE_ENDPOINT" | "STORAGE_BUCKET" | "STORAGE_ACCESS_KEY" | "STORAGE_SECRET_KEY" | "STORAGE_PUBLIC_BASE_URL" | "PAYMENT_PROVIDER" | "PAYMENT_WEBHOOK_ALLOWED_IPS" | "MOCK_WEBHOOK_SECRET" | "ECPAY_MERCHANT_ID" | "ECPAY_HASH_KEY" | "ECPAY_HASH_IV" | "ECPAY_ENDPOINT" | "NEWEBPAY_MERCHANT_ID" | "NEWEBPAY_HASH_KEY" | "NEWEBPAY_HASH_IV" | "TAPPAY_PARTNER_KEY" | "TAPPAY_MERCHANT_ID" | "TAPPAY_APP_ID" | "TAPPAY_APP_KEY" | "ORDER_EXPIRE_MINUTES" | "BUSINESS_DAY_CUTOFF">> {}
}
